# Setup
title:            Nathan Fieldsteel
tagline:          ''
description:      'Mathematical software and computation'
url:              ''
baseurl:          ''
paginate:         5


# About and contact
author:
  name:           'Nathan Fieldsteel'

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-katex

# Custom vars
sidebar-name:	N Fieldsteel
version:    	3.0.0

site.github.repo:	  github.com/nathanfieldsteel